//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemperatureForm.TempService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusToFahrenheitResponse")]
        double CelsiusToFahrenheit(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusToFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitToCelsiusResponse")]
        double FahrenheitToCelsius(double f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitToCelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double f);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TemperatureForm.TempService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TemperatureForm.TempService.IService1>, TemperatureForm.TempService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CelsiusToFahrenheit(double c) {
            return base.Channel.CelsiusToFahrenheit(c);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double c) {
            return base.Channel.CelsiusToFahrenheitAsync(c);
        }
        
        public double FahrenheitToCelsius(double f) {
            return base.Channel.FahrenheitToCelsius(f);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double f) {
            return base.Channel.FahrenheitToCelsiusAsync(f);
        }
    }
}
